### ISSUE TITLE
Create a `Terms of Use` Document

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#126]
### **Description**:
We need to draft a comprehensive `Terms of Use` document for our platform. This document will outline the rules and guidelines that users must agree to and follow in order to use our platform. It will also cover the legal aspects and user responsibilities.

### **Tasks**:
- [ ] Research standard `Terms of Use` templates and best practices.
- [ ] Draft an initial version of the `Terms of Use`.
- [ ] Review the document with the legal team or consultant.
- [ ] Incorporate feedback and finalize the document.
- [ ] Add the `Terms of Use` to the platform, ensuring users can access it easily.
- [ ] Implement a mechanism to get user agreement on the `Terms of Use` during sign-up or first login.

### **Additional Information**:
- The document should cover aspects like user responsibilities, prohibited activities, disclaimers, limitation of liability, and termination of service.
- It should be written in clear, understandable language.
- Consider international users and any regional legal requirements.

**Comment by mufniarz** [comment]
Created [Terms of Use](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/wiki/Terms-of-Use-%E2%80%90-ASCENDynamics-NFP-Collaborative-Nonprofit-Network-(CNN))
